Catkin-ProjectName: genmsg
Version: 0.1.7
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Ken Conley
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Depends: catkin

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: python_distutils

Release-Pull: git://github.com/wg-debs/genmsg.git
Release-Push: git@github.com:wg-debs/genmsg.git
