Package: genmsg
Version: 0.1.2
Section: misc
Priority: extra
Architecture: all
Depends: python-empy, cmake, make
Build-Depends: cmake, python, python-empy, @(PackagePrefix)catkin
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Ken Conley
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org
Catkin-DebRulesType: python_distutils
Catkin-CopyrightType:  willowgarage
Catkin-Depends: catkin
Catkin-ProjectName: genmsg
